### ISSUE TITLE
Deployed app - landing page image hidden

### ISSUE THREAD

**Issue by lisamsmith100** [ga-wdi-boston/group-project#298]
SOS!  Not sure why, but our deployed app (lots not deployed yet but...)
How can I fix this hidden image?  
Here is the deployed app:
https://threes-amigos.github.io/three-amigos-client/

(again, still have plenty to deploy but not sure how to fix this).

Our localhost version looks like this (without signing in):

<img width="1414" alt="screen shot 2017-05-18 at 8 13 53 pm" src="https://cloud.githubusercontent.com/assets/26127720/26228311/b9f700c8-3c06-11e7-9cb7-2ceff87151cd.png">

**Comment by lisamsmith100** [comment]
Because this is bootstrap, we have followed the template and added the url in the template css:
```css
.intro-header {
    padding-top: 50px; /* If you're making other pages, make sure there is 50px of padding to make sure the navbar doesn't overlap content! */
    padding-bottom: 50px;
    text-align: center;
    /*color: #067a6b;*/
    color: black;
    background: url(https://cloud.githubusercontent.com/assets/26127720/26208950/68ebef88-3bb9-11e7-820f-b80c232d51d8.jpg) no-repeat center center;
    /*background-size: cover;*/
    background-size: contain;
    font-weight:600;
}
```
