### ISSUE TITLE
css - style sheet code not being picked up 

### ISSUE THREAD

**Issue by artpylon** [ga-wdi-boston/group-project#361]
I have a small number of css rules in my styles.scss, but they aren't being picked up when I test locally. Previously, they were working:

```css
$icon-font-path: '~bootstrap-sass/assets/fonts/bootstrap/';
@import '~bootstrap-sass/assets/stylesheets/bootstrap';

.files-list-container {
  display: none;

},

.folder-list-container {
  display: none;

},

.file-uploader {
  padding-bottom: 10px;

},

.modal-buttons {
  padding-bottom: 20px;

},

.below-modal-title {
  padding-top: 10px;

}
```
